import { Injectable, signal } from '@angular/core';
import { Stat, Feature, Service, TimelineStage } from '../models/content.model';
import { Testimonial } from '../models/testimonial.model';
import { FaqItem } from '../models/faq-item.model';
import { ConstructionPackage } from '../models/construction-package.model';
import { ProcessStep } from '../models/process-step.model';
import { Project } from '../models/project.model';
import { SITE_IMAGES, PROJECT_IMAGES } from '../constants/site.images';

@Injectable({ providedIn: 'root' })
export class SiteDataService {
  readonly stats = signal<Stat[]>([
    { value: 10, suffix: '+', label: 'Years Experience' },
    { value: 150, suffix: '+', label: 'Homes Delivered' },
    { value: 25, suffix: '+', label: 'Design Professionals' },
    { value: 100, suffix: '%', label: 'Client Focus' },
  ]);

  readonly features = signal<Feature[]>([
    { id: 1, index: '01', title: 'Transparent Pricing', icon: 'file', description: 'Itemised quotes with no hidden costs. You know exactly what every rupee builds.' },
    { id: 2, index: '02', title: 'Quality Materials', icon: 'shield', description: 'Branded steel, cement and finishes vetted through strict material inspection.' },
    { id: 3, index: '03', title: 'Dedicated Project Management', icon: 'users', description: 'A single point of contact overseeing every milestone from digging to handover.' },
    { id: 4, index: '04', title: 'Professional Design', icon: 'pen', description: 'Architectural plans engineered for light, ventilation and lasting value.' },
    { id: 5, index: '05', title: 'Milestone-Based Payments', icon: 'calendar', description: 'Pay stage by stage — only as each phase of construction is completed.' },
    { id: 6, index: '06', title: 'On-Time Execution', icon: 'clock', description: 'A disciplined construction schedule with weekly progress reports.' },
    { id: 7, index: '07', title: 'Complete Construction Support', icon: 'building', description: 'Approvals, supervision, MEP and finishing — handled end to end.' },
    { id: 8, index: '08', title: 'Long-Term Structural Quality', icon: 'award', description: 'Earthquake-conscious frames built to serve generations, not seasons.' },
  ]);

  readonly services = signal<Service[]>([
    { id: 'home-construction', title: 'Home Construction', icon: 'building', description: 'Complete design-to-handover construction of durable, beautiful homes.' },
    { id: 'architectural-design', title: 'Architectural Design', icon: 'pen', description: 'Plans tuned to your plot, climate and how your family actually lives.' },
    { id: 'structural-design', title: 'Structural Design', icon: 'grid', description: 'Approved structural drawings engineered for safety and longevity.' },
    { id: 'interior-solutions', title: 'Interior Solutions', icon: 'armchair', description: 'Flowing interiors that bring the architecture to life.' },
    { id: 'renovation', title: 'Renovation', icon: 'hammer', description: 'Thoughtful upgrades that give your existing home a new life.' },
  ]);

  readonly testimonials = signal<Testimonial[]>([
    { id: 1, name: 'Mr. Aarumugam', location: 'Vandalur, Chennai', project: 'G+1 Independent House', rating: 5, quote: 'They handed over our home three weeks early with zero deviation from the quoted price. Every milestone was documented on WhatsApp. Truly professional.' },
    { id: 2, name: 'Mrs. Meenakshi Natarajan', location: 'Perumbakkam, Chennai', project: 'Premium Villa', rating: 5, quote: 'Classic Jack felt like an architectural studio, not a contractor. The design process alone was worth it — our home is flooded with natural light.' },
    { id: 3, name: 'Mr. Chandrasekar', location: 'Mahindra World City', project: 'G+2 Residence', rating: 5, quote: 'The milestone-based payments gave us full control. We always knew where our money was going and what was being built next.' },
    { id: 4, name: 'Dr. Selvaraj', location: 'Tambaram, Chennai', project: 'Premium Independent House', rating: 5, quote: 'From soil testing to the final key handover, everything was planned. The structural quality is excellent and the finishing is outstanding.' },
    { id: 5, name: 'Mrs. Kavitha Venkatesh', location: 'Chengalpattu', project: 'G+1 Residence', rating: 4, quote: 'Transparent pricing and clear communication. Our neighbours thought the house was fully built by an architect — it was that precise.' },
    { id: 6, name: 'Mr. Karthik Vasanth', location: 'Navallur, Chennai', project: 'Luxury Villa', rating: 5, quote: 'We compared four companies and Classic Jack won on specification clarity. Six months after move-in, everything still feels brand new.' },
  ]);

  readonly faqs = signal<FaqItem[]>([
    { id: 1, question: 'What is the approximate construction cost per sq.ft?', answer: 'Our packages start at ₹1,999 per sq.ft for the Budget package and go up to ₹2,899 per sq.ft for Luxury. The final cost depends on design, flooring, materials and site conditions. Use our construction cost calculator for an indicative estimate.' },
    { id: 2, question: 'How long does it take to build a house?', answer: 'A typical G+1 house takes 12–16 months from approval to handover. Larger structures like G+2 or G+3 homes may take 18–24 months, depending on design and season.' },
    { id: 3, question: 'Do you handle architectural design?', answer: 'Yes. Our in-house design team prepares architectural plans, 3D views and working drawings. We refine the plan with you until every room feels right before construction begins.' },
    { id: 4, question: 'Do you handle government approvals?', answer: 'We manage the complete approval process — building permits, plan sanctions and compliance documentation — with local authorities, so you do not have to run around.' },
    { id: 5, question: 'Do you provide structural drawings?', answer: 'Absolutely. Every project gets approved structural drawings and load calculations prepared by qualified structural engineers, before any concrete is poured.' },
    { id: 6, question: 'How are payments handled?', answer: 'Through milestone-based payments. You pay per completed stage — excavation, foundation, structure, brickwork, finishes — giving you full control and visibility over your budget.' },
    { id: 7, question: 'Do you provide a warranty?', answer: 'Yes. Every home comes with a structural warranty and a service warranty on finishes. Our team also provides free post-handover support for a defined period.' },
    { id: 8, question: 'Can I customise the floor plan?', answer: 'Yes. Our floor plans are starting points, not constraints. We customise layouts, room sizes, ceiling heights and elevation styles to match how your family lives.' },
    { id: 9, question: 'Do you build G+1, G+2 and G+3 houses?', answer: 'Yes, we build single-storey through G+3 structures, subject to local zoning rules. Our structural team designs each frame specifically for its storey count and soil type.' },
    { id: 10, question: 'Which locations do you cover?', answer: 'We primarily serve Chennai, Chengalpattu, Kanchipuram, Tiruvallur, Vellore and Pondicherry. For large projects we are happy to discuss other locations.' },
    { id: 11, question: 'Can I upgrade materials?', answer: 'Yes. Every package has an upgrade path. You can switch brands, upgrade flooring, joinery or fixtures anytime — we adjust the estimate transparently before work begins.' },
  ]);

  readonly packages = signal<ConstructionPackage[]>([
    {
      id: 'budget',
      name: 'Budget',
      pricePerSqft: 1999,
      tagline: 'Functional & sturdy',
      description: 'A practical, durable home built with standard branded materials and clean finishes.',
      image: SITE_IMAGES.packages.budget,
      features: [
        'Standard branded cement & steel',
        'Basic ceramic tile flooring',
        'Standard electrical points',
        'Ready-to-paint wall putty',
        'RCC framed structure',
      ],
      materials: 'Standard branded cement & TMT steel with copies of test certificates.',
      structural: 'RCC framed structure with M20 grade concrete.',
      electrical: 'Standard single-phase wiring with quality modular switches.',
      plumbing: 'Concealed CPVC water supply with branded bathroom fittings.',
      flooring: 'Vitrified / ceramic tile flooring in living, bedrooms & kitchen.',
      painting: 'Waterproofing + putty + 2 coats of premium emulsion.',
      doorsWindows: 'Teak / commercial ply flush doors with powder-coated aluminium windows.',
      warranty: '5-year structural warranty · 1-year services warranty.',
      deliveredIn: '12 – 14 months',
    },
    {
      id: 'standard',
      name: 'Standard',
      pricePerSqft: 2299,
      tagline: 'Quality with comfort',
      description: 'Stronger specifications and better finishes for everyday family living.',
      image: SITE_IMAGES.packages.standard,
      features: [
        'Superior branded cement & steel',
        'Vitrified tiles upgraded',
        'Inverter-grade power provisioning',
        'False ceiling in living area',
        'Double-glazed aluminium windows',
        'Designer elevation',
      ],
      materials: 'Superior branded cement & Fe500 D TMT steel with batch test certificates.',
      structural: 'RCC framed structure with M25 grade concrete & seismic design.',
      electrical: 'Copper wiring with modular switches, TV & internet conduits.',
      plumbing: 'Concealed CPVC/UPVC piping with branded premium sanitaryware.',
      flooring: 'Premium certified vitrified tiles with skirting matching.',
      painting: 'Waterproofing + putty + exterior texture + premium interior emulsion.',
      doorsWindows: 'Premium flush doors in teak frame with uPVC / aluminium sliding windows.',
      warranty: '5-year structural warranty · 2-year services warranty.',
      deliveredIn: '13 – 16 months',
    },
    {
      id: 'premium',
      name: 'Premium',
      pricePerSqft: 2599,
      tagline: 'Elevated living',
      description: 'Architectural detailing, premium finishes and engineered comfort.',
      image: SITE_IMAGES.packages.premium,
      features: [
        'Premium branded cement & steel',
        'Branded tiles / natural stone options',
        '3-phase power provisioning',
        'POP & designer false ceiling',
        'Premium joinery & hardware',
        'Fully designed elevation',
        'Energy-efficient lighting layout',
      ],
      materials: 'Premium branded cement & high-grade TMT steel with full documentation.',
      structural: 'RCC framed structure with M25/M30 concrete & earthquake-resistant design.',
      electrical: 'Multi-point copper wiring, 3-phase provision, smart-ready conduits.',
      plumbing: 'Full concealed plumbing with branded fixtures, sump & overhead tank plan.',
      flooring: 'Branded vitrified / imported tiles or engineered wood options.',
      painting: 'Premium vapour-core interiors, designer textures & exterior paint system.',
      doorsWindows: 'Designer flush / panel doors with premium hardware and UPVC windows.',
      warranty: '10-year structural warranty · 2-year services warranty.',
      deliveredIn: '15 – 18 months',
    },
    {
      id: 'luxury',
      name: 'Luxury',
      pricePerSqft: 2899,
      tagline: 'The statement home',
      description: 'Bespoke architecture, imported materials and a fully curated home experience.',
      image: SITE_IMAGES.packages.luxury,
      features: [
        'Bespoke architectural design',
        'Natural stone & imported tiles',
        'Smart home pre-wiring',
        'Designer lighting & facades',
        'Premium branded sanitaryware',
        'Elevation with 3D visualisation',
        'Landscape & outdoor planning',
        'White-glove handover',
      ],
      materials: 'Top-grade materials with sourcing certificates for every major input.',
      structural: 'High-spec RCC frame with premium M30+ concrete & advanced seismic detailing.',
      electrical: 'Full smart-home pre-wiring, designer lighting automation readiness.',
      plumbing: 'Premium copper / PPR piping, designer sanitaryware & rainwater harvesting.',
      flooring: 'Natural stone, imported porcelain or engineered wood across the home.',
      painting: 'Premium imported paints, feature textures & designer wall finishes.',
      doorsWindows: 'Flush / louvred designer doors, premium hardware & performance glass.',
      warranty: '10-year structural warranty · 3-year services warranty.',
      deliveredIn: '18 – 24 months',
    },
  ]);

  readonly processSteps = signal<ProcessStep[]>([
    { id: 1, index: '01', title: 'Initial Consultation', duration: 'Week 1', image: SITE_IMAGES.blueprint.lines, description: 'We listen. Understanding your plot, family needs, budget and lifestyle shapes every decision that follows.' },
    { id: 2, index: '02', title: 'Site & Soil Analysis', duration: 'Week 1–2', image: SITE_IMAGES.timeline.foundation, description: 'Soil testing, plot orientation and site survey guide the foundation and structural design.' },
    { id: 3, index: '03', title: 'Architectural & Floor Plan Design', duration: 'Week 2–5', image: SITE_IMAGES.blueprint.lines, description: 'Our architects draft floor plans and 3D elevations you can walk through before we build.' },
    { id: 4, index: '04', title: 'Approval & Agreement', duration: 'Week 5–8', image: SITE_IMAGES.blueprint.lines, description: 'Drawings get sanctioned, agreements are signed and a milestone payment schedule is fixed.' },
    { id: 5, index: '05', title: 'Foundation & Structural Construction', duration: 'Month 2–5', image: SITE_IMAGES.timeline.foundation, description: 'Excavation, foundation and the RCC frame rise, with quality checks at every pour.' },
    { id: 6, index: '06', title: 'Electrical & Plumbing', duration: 'Month 5–8', image: SITE_IMAGES.timeline.structure, description: 'Concealed MEP networks are laid and tested inside the structure.' },
    { id: 7, index: '07', title: 'Flooring, Painting & Finishing', duration: 'Month 8–11', image: SITE_IMAGES.timeline.interiors, description: 'Flooring, paint, doors and fixtures transform the frame into a home.' },
    { id: 8, index: '08', title: 'Final Inspection & Key Handover', duration: 'Month 12+', image: SITE_IMAGES.timeline.completed, description: 'A step-by-step walkthrough, warranty documentation and the moment you receive your keys.' },
  ]);

  readonly timelineStages = signal<TimelineStage[]>([
    { id: 'empty', label: 'Empty Land', description: 'Every legacy begins as soil.', progress: 0, image: SITE_IMAGES.timeline.plot },
    { id: 'foundation', label: 'Foundation', description: 'Footings take hold of the earth.', progress: 14, image: SITE_IMAGES.timeline.foundation },
    { id: 'structure', label: 'Structure', description: 'The RCC frame climbs skyward.', progress: 33, image: SITE_IMAGES.timeline.structure },
    { id: 'brickwork', label: 'Brickwork', description: 'Walls give the frame a voice.', progress: 50, image: SITE_IMAGES.timeline.brickwork },
    { id: 'plastering', label: 'Plastering', description: 'Skin smooths the silhouette.', progress: 66, image: SITE_IMAGES.timeline.structure },
    { id: 'interiors', label: 'Interiors', description: 'Light, wood and stone arrive.', progress: 85, image: SITE_IMAGES.timeline.interiors },
    { id: 'completed', label: 'Completed Home', description: 'Architecture becomes address.', progress: 97, image: SITE_IMAGES.timeline.completed },
    { id: 'handover', label: 'Key Handover', description: 'Legacy, delivered.', progress: 100, image: SITE_IMAGES.timeline.completed },
  ]);

  readonly projects = signal<Project[]>([
    {
      id: 'aarumugam-residence',
      name: 'Mr. Aarumugam Residence',
      client: 'Mr. Aarumugam',
      location: 'Vandalur, Chennai',
      builtUpArea: 1800,
      floors: 2,
      type: 'Independent House',
      status: 'Completed',
      year: '2024',
      tagline: 'A G+1 home shaped around courtyard light.',
      description: 'Designed around a central shaft of light, this G+1 home gives every room a quiet connection to the outdoors while maximising privacy on a mid-size plot.',
      image: PROJECT_IMAGES.aarumugam,
      gallery: [PROJECT_IMAGES.aarumugam, PROJECT_IMAGES.interior2, PROJECT_IMAGES.interior5, PROJECT_IMAGES.interior4],
      design: 'The elevation balances deep concrete bands with warm wood screens. An internal court pulls daylight into the staircase and living zone.',
      construction: 'RCC framed structure on compacted soil with M25 concrete, executed in 14 months with fully documented material tests.',
      result: 'A low-maintenance, light-filled home that the family describes as “calm from the moment you step in”.',
      featured: true,
    },
    {
      id: 'murali-villa',
      name: 'Murali Villa',
      client: 'Mr. Murali',
      location: 'Navallur, OMR',
      builtUpArea: 3200,
      floors: 2,
      type: 'Villa',
      status: 'Completed',
      year: '2023',
      tagline: 'A double-height villa with a pool courtyard.',
      image: PROJECT_IMAGES.murali,
      gallery: [PROJECT_IMAGES.murali, PROJECT_IMAGES.interior1, PROJECT_IMAGES.villa, PROJECT_IMAGES.interior6],
      description: 'A double-height living volume wrapped around a private pool courtyard — engineered Vastu-compliant plan with a modern architectural skin.',
      design: 'Floor-to-ceiling glass along the courtyard dissolves the line between pool and interior, while a deep verandah shades the western facade.',
      construction: 'Premium M30 structural frame, high-grade finishes and a fully concealed MEP network delivered in 18 months.',
      result: 'A statement villa that photographs like a resort yet functions as a warm family home.',
      featured: true,
    },
    {
      id: 'natarajan-residence',
      name: 'Natarajan Residence',
      client: 'Mrs. Meenakshi Natarajan',
      location: 'Perumbakkam, Chennai',
      builtUpArea: 2400,
      floors: 3,
      type: 'Independent House',
      status: 'Completed',
      year: '2024',
      tagline: 'A G+2 home with a roof terrace garden.',
      image: PROJECT_IMAGES.natarajan,
      gallery: [PROJECT_IMAGES.natarajan, PROJECT_IMAGES.interior3, PROJECT_IMAGES.interior8, PROJECT_IMAGES.facade2],
      description: 'A three-storey residence designed for a multigenerational family, with independent wings that share a common dining heart.',
      design: 'The plan separates parents and children into distinct zones while a generous staircase landing becomes the family library.',
      construction: 'Earthquake-conscious G+2 frame, completed on schedule with milestone-based payments at every stage.',
      result: 'A future-ready home where three generations live together without crowding each other.',
      featured: true,
    },
    {
      id: 'chandrasekar-residence',
      name: 'Chandrasekar Residence',
      client: 'Mr. Chandrasekar',
      location: 'Mahindra World City',
      builtUpArea: 2800,
      floors: 3,
      type: 'Villa',
      status: 'Completed',
      year: '2022',
      tagline: 'A minimal elevation with a warm, textured heart.',
      image: PROJECT_IMAGES.chandrasekar,
      gallery: [PROJECT_IMAGES.chandrasekar, PROJECT_IMAGES.interior7, PROJECT_IMAGES.interior4, PROJECT_IMAGES.facade1],
      description: 'Bare concrete, clear glass and warm teak meet in a layout planned for small townhouses style living.',
      design: 'The ground floor flows openly to a back garden. Upstairs, deep window reveals frame the horizon.',
      construction: 'Precise formwork gave the exposed concrete its gallery-like finish.',
      result: 'A refined, clutter-free interior with maintenance kept deliberately low.',
      featured: false,
    },
    {
      id: 'selvaraj-residence',
      name: 'Dr. Selvaraj Residence',
      client: 'Dr. Selvaraj',
      location: 'Tambaram, Chennai',
      builtUpArea: 2200,
      floors: 2,
      type: 'Independent House',
      status: 'Completed',
      year: '2023',
      tagline: 'A wellness-focused G+1 home with a healing court.',
      image: PROJECT_IMAGES.selvaraj,
      gallery: [PROJECT_IMAGES.selvaraj, PROJECT_IMAGES.interior5, PROJECT_IMAGES.interior2, PROJECT_IMAGES.villa],
      description: 'Designed with a doctor’s eye for calm — a skylit court, silent zone and materials chosen for air quality.',
      design: 'Cross ventilation runs through every bedroom, and the study is placed in the quietest corner of the plan.',
      construction: 'Careful scheduling around two monsoons kept the 15-month program intact.',
      result: 'A home that feels airy even in Chennai’s humid months.',
      featured: false,
    },
    {
      id: 'vasanth-residence',
      name: 'Karthik Vasanth Residence',
      client: 'Mr. Karthik Vasanth',
      location: 'Vandalur, Chennai',
      builtUpArea: 1950,
      floors: 2,
      type: 'Residence',
      status: 'Ongoing',
      year: '2025',
      tagline: 'Now rising — a warm contemporary family home.',
      image: PROJECT_IMAGES.vasanth,
      gallery: [PROJECT_IMAGES.vasanth, PROJECT_IMAGES.interior6, PROJECT_IMAGES.interior1, PROJECT_IMAGES.facade2],
      description: 'Currently in its finishing stage, this contemporary home pairs a warm grey palette with timber accents and a planned home-office wing.',
      design: 'The elevation steps back at first floor, creating a shaded verandah and visual rhythm.',
      construction: 'Structural frame and brickwork complete; interiors and services in progress.',
      result: 'Expected handover in the coming season.',
      featured: false,
    },
    {
      id: 'venkatesh-residence',
      name: 'Venkatesh Residence',
      client: 'Mrs. Kavitha Venkatesh',
      location: 'Chengalpattu',
      builtUpArea: 2100,
      floors: 2,
      type: 'Independent House',
      status: 'Completed',
      year: '2021',
      tagline: 'A south-facing plan that celebrates the corner plot.',
      image: PROJECT_IMAGES.venkatesh,
      gallery: [PROJECT_IMAGES.venkatesh, PROJECT_IMAGES.interior3, PROJECT_IMAGES.interior8, PROJECT_IMAGES.facade1],
      description: 'A corner-plot home that opens its living spine to two streets of moving shade and dappled light.',
      design: 'The corner is pulled back into a landscaped threshold, gifting the street a green pause.',
      construction: 'Efficient framing and prefabricated stairs cut four weeks from the schedule.',
      result: 'A four-year-old home that still draws compliments from passing neighbours.',
      featured: false,
    },
  ]);

  constructor() {
    // Data is intentionally synchronous + local today.
    // Swap these signals with HttpClient-backed observables when the .NET API lands.
  }
}